### ISSUE TITLE
Simplify Block Scan Status(Tracker)

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#284]
https://github.com/darwinia-network/bridger/blob/b2316d4de0150770f926214b8b3962716fea77b8/supports/support-tracker/src/lib.rs#L6-L15

- [ ] Remove `key_raw`
- [ ] Rename `key_curt ` to `key_current`
- [ ] Remove `key_finish `, use key_current - 1 instead
- [ ] Remove `key_next ` or rename to `key_planned`
- [ ] Why we need `key_skipped `? Remove it?
- [ ] Remove `key_fast_mode `

**Comment by HackFisher** [comment]
The scan service could be replaced by indexers like subquery and theGraph, other services just use GraphaQL api of indexrs to query and process.

Tracker is more like a progress concept, and planned feature should be move to specific services such as redeem service etc.

Check service might be necessary, since with the indexer apis, bridger will be easily to query the status.
