### ISSUE TITLE
Bridger and shadow next version checklist

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#423]
To simplify the design of shadow, we are going to use theGraph as the indexer of Ethereum header MMR, instead of current indexing implementation in shadow. This could simplify the design and operation of shadow service, btw, it will also eliminate the necessary of operating geth node(for mmr import usage).

Here are the todos and checklist:

- [x] Deploy mmr subgraph for Ethereum mainnet using theGrpha's hosted servcie. cc @xiaoch05  https://api.thegraph.com/subgraphs/name/darwinia-network/ethereum-mmr
- [x] Deploy mmr subgraph for ropsten testnet using theGrpha's hosted servcie. cc @xiaoch05 https://api.thegraph.com/subgraphs/name/darwinia-network/ropsten-mmr
- [x] New library to generate mmr proof using theGraph api.  @fewensa @xiaoch05 
  - WIP PR: https://github.com/darwinia-network/shadow/pull/165   This is used for get proof nodes position from member_leaf_index and last_leaf_index
  - Using return value of above PR, to retrieve hash nodes from theGraph by their positions, and reassemble them into same proof data as legacy api
- [x] Replace MMR related api calls in bridger using new solution, and integration test. @fewensa 
- [x] Remove mmr related codes in new version of shadow. And deploy a new shadow service using new version, update/remove services. @fewensa 
- [ ] Archive the old version and documents for shadow. The mmr import features in deprecated shadow is still useful for validation and testing. @xiaoch05 

Related:
https://github.com/darwinia-network/darwinia-bridge-sol/pull/123
#400
